requires = [ "tox>=4.23", ]
envlist = [ "py310", "py311", "py312", ]

[env_run_base]
description = "Run test under {base_python}"
deps = ["pytest"]
commands = [
    [ "pytest", { replace = "posargs", default = [ "tests", ], extend = true }, ],
]
